Foreground true
LogTime true
LogClean false
LogVerbose false
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
MaxConnectionQueueLength 30
MaxThreads 4
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 120
MaxScanTime 120000
MaxScanSize 100M
MaxFileSize 25M
MaxRecursion 16
MaxFiles 10000
StreamMaxLength 25M
AlertEncrypted true
DetectPUA false
