from app.models.auth import (
    AuditEvent,
    Institution,
    InstitutionDomain,
    InstitutionMembership,
    InstitutionRegistrationRequest,
    MembershipInvitation,
    MfaEnrollment,
    MfaRecoveryCode,
    PasswordResetToken,
    RosterImport,
    RosterImportRow,
    Session,
    StudentRegistrationRequest,
    TermsAcceptance,
    User,
)
from app.models.base import Base
from app.models.communications import (
    CommunicationPreference,
    EmailDelivery,
    ProductEvent,
    SupportRequest,
)
from app.models.engagement import (
    InAppNotification,
    RoadmapProgress,
    RoadmapTemplate,
    StudentRoadmap,
)
from app.models.experience import CorrectionEvent, CorrectionRequest, SavedOpportunityView
from app.models.generative_ai import (
    AiAcceptedFieldProvenance,
    AiConversation,
    AiGenerationProposal,
    AiMessage,
    AiToolRun,
)
from app.models.intelligence import PolicyDocument, RoleExtractionProposal, SemanticMatchEvidence
from app.models.onboarding import (
    InstitutionCampus,
    InstitutionFeatureFlags,
    InstitutionOnboarding,
    InstitutionProgram,
    StudentCareerPreference,
    StudentCertification,
    StudentEducation,
    StudentExperience,
    StudentPlacementParticipation,
    StudentProject,
)
from app.models.privacy import DataDeletionRequest
from app.models.profile import ProfilePhoto, StudentProfile
from app.models.recruitment import (
    Application,
    ApplicationAppeal,
    ApplicationDisclosure,
    ApplicationDisclosureDraft,
    ApplicationDraft,
    ApplicationOverride,
    ApplicationStatusEvent,
    Company,
    EligibilityEvaluation,
    EligibilityRuleSet,
    PlacementDrive,
    PlacementRole,
    RoleApplicationForm,
    SavedOpportunity,
)
from app.models.resume import (
    Resume,
    ResumeJobEvent,
    ResumeProcessingJob,
    ResumeSuggestion,
    ResumeVersion,
)

__all__ = [
    "ProfilePhoto",
    "CorrectionEvent",
    "CorrectionRequest",
    "SavedOpportunityView",
    "AuditEvent",
    "AiAcceptedFieldProvenance",
    "AiConversation",
    "AiGenerationProposal",
    "AiMessage",
    "AiToolRun",
    "Application",
    "ApplicationAppeal",
    "ApplicationDisclosure",
    "ApplicationDisclosureDraft",
    "ApplicationDraft",
    "ApplicationOverride",
    "ApplicationStatusEvent",
    "Base",
    "CommunicationPreference",
    "EmailDelivery",
    "InAppNotification",
    "PolicyDocument",
    "ProductEvent",
    "RoleExtractionProposal",
    "RoadmapProgress",
    "RoadmapTemplate",
    "SemanticMatchEvidence",
    "Company",
    "DataDeletionRequest",
    "EligibilityEvaluation",
    "EligibilityRuleSet",
    "Institution",
    "InstitutionDomain",
    "InstitutionMembership",
    "InstitutionRegistrationRequest",
    "InstitutionCampus",
    "InstitutionFeatureFlags",
    "InstitutionOnboarding",
    "InstitutionProgram",
    "MembershipInvitation",
    "MfaEnrollment",
    "MfaRecoveryCode",
    "PasswordResetToken",
    "PlacementDrive",
    "PlacementRole",
    "RoleApplicationForm",
    "Resume",
    "ResumeJobEvent",
    "ResumeProcessingJob",
    "ResumeSuggestion",
    "ResumeVersion",
    "RosterImport",
    "RosterImportRow",
    "SavedOpportunity",
    "Session",
    "StudentProfile",
    "StudentCareerPreference",
    "StudentCertification",
    "StudentEducation",
    "StudentExperience",
    "StudentPlacementParticipation",
    "StudentProject",
    "StudentRegistrationRequest",
    "StudentRoadmap",
    "SupportRequest",
    "TermsAcceptance",
    "User",
]
